id: I6635FCDF
default_language: pt
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:23.545718
last_modified: 2023-01-04 11:30:23.545734
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  610D:
    title: The Benefits of Saving Lives
    base_file: 610D.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
